{% set version = "0.4.7" %}

package:
  name: xonsh
  version: {{ version }}

source:
  fn: xonsh-{{ version }}.tar.gz
  url: https://github.com/xonsh/xonsh/archive/{{ version }}.tar.gz
  sha256: 10732db7a635b94454232f389f1960a27736e63bb3ce7daf6dc59fda7d5f5abb

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt  # [not win]
  entry_points:
    - xonsh = xonsh.main:main
  skip: True  # [py2k]
  number: 1

requirements:
  build:
    - python
    - ply
    - setuptools
    - jupyter
  run:
    - python
    - ply
    - prompt_toolkit
    - pygments
    - setproctitle

test:
  requires:
    - pytest
  imports:
    - xonsh
  commands:
    - USER=test xonsh -h  # [unix]
    - xonsh -h  # [win]

app:
  entry: xonsh
  icon: xonsh.png
  summary: xonsh is a Python-ish, BASHwards-facing shell.
  type: desk

about:
  home: http://xon.sh
  license: BSD 2-Clause
  summary: xonsh is a Python-ish, BASHwards-facing shell.
  description: |
    Xonsh is a Python-ish, BASHwards-looking shell language and command prompt.
    The language is a superset of Python 3.4+ with additional shell primitives
    that you are used to from Bash and IPython. It works on all major systems
    including Linux, Mac OSX, and Windows. Xonsh is meant for the daily use
    of experts and novices alike.
  doc_url: http://xon.sh
  dev_url: https://github.com/scopatz/xonsh

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
    - melund
