{% set version = "0.2.7" %}

package:
  name: xonsh
  version: {{ version }}

source:
  fn: xonsh-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/x/xonsh/xonsh-{{ version }}.tar.gz
  md5: b810500337fb43b21a03146cdf30d6b5

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt  # [not win]
  entry_points:
    - xonsh = xonsh.main:main
  skip: True  # [py2k]
  number: 0

requirements:
  build:
    - python
    - ply
    - setuptools
    - jupyter
  run:
    - python
    - ply
    - prompt_toolkit
    - pygments
    - setproctitle

test:
  requires:
    - nose
  imports:
    - xonsh
  commands:
    - xonsh -h

app:
  entry: xonsh
  icon: xonsh.png
  summary: xonsh is a Python-ish, BASHwards-facing shell.
  type: desk

about:
  home: http://xon.sh
  license: BSD
  summary: xonsh is a Python-ish, BASHwards-facing shell.
  description: |
    Xonsh is a Python-ish, BASHwards-looking shell language and command prompt.
    The language is a superset of Python 3.4+ with additional shell primitives 
    that you are used to from Bash and IPython. It works on all major systems 
    including Linux, Mac OSX, and Windows. Xonsh is meant for the daily use 
    of experts and novices alike.
  doc_url: http://xon.sh
  dev_url: http://github.com/scopatz/xonsh

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
    - melund
