travis:
  secure:
    BINSTAR_TOKEN: Ru+8OSEftNjDZXOMIc8I9wfHy9aoU8Vyhr2Y4t4ZdXY80FeNUpoEig64etE3lnj8X8xVIEpUe83kQY5YSGjH6AHCfMDiPvgiWDeiHpy3/hdhJHvzzEYx6O3d9QPy+sHOAlQ+QKof7iWmWFL9/W07HBrdgnTvJzIcMukflbPxoOXX+3pjvBE5UJP/FfjMI/pGzcQvkTZdhPf9e1o2bhCA/LxfZ0aN3bEwlj9nFney3NsFVFjquTmPmigeYhklZLkb/+1uZQr81XL00cwrbFzeFFiIjNz1vS/DCQqTxe5Y7u186kJMVRPhzjYDo7wnpPNj3mpW4ovONTrdUpB2NcZ7384J0shRiDiZxFCFMc5Fs0oO84DNkdD2qkTV19nnGw6wF8Qi0mHe89EGiFu5KK2Im2LN8HQVSlxU0GkCsAIh7aUuNvXnDIKHSZbrF47hKKkU2ENXe/xKNaTVVkg3R7MoJjeEzs2tNVEKPTfDnJtrfIoDPsm0+geU91qXVDmurM9xqNKw6kzDGZK7nKwu8azcnrD5bQwXZ7JKfx6MESh50vJ2cE5XKtw92Dh2QbvmMWzHHoqmCCJbyursXRlsCUS+h+Ltn1Raxg4WZ0bQUqi+jHfhzQ+TPFsQhtL7W+G0J+8HO/F9K+AREuYIPg047HTNK1CilS9x9xhUqDP2ovkVnKg=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
